"""Update doctor notes schema

Revision ID: 3e93139606e3
Revises: 3ac1ee79ee58
Create Date: 2025-06-29 16:24:26.085324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e93139606e3'
down_revision = '3ac1ee79ee58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prescription', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_notes', schema=None) as batch_op:
        batch_op.drop_column('prescription')
        batch_op.drop_column('diagnosis')

    # ### end Alembic commands ###
