"""Fix doctor_notes: add appointment_id, rename leave_days

Revision ID: aa4e3b7dcc10
Revises: 3e93139606e3
Create Date: 2025-06-29 18:44:37.506894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4e3b7dcc10'
down_revision = '3e93139606e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('leave_days', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_doctor_notes_appointment_id_appointments'), 'appointments', ['appointment_id'], ['id'])
        batch_op.drop_column('leave_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_duration', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_doctor_notes_appointment_id_appointments'), type_='foreignkey')
        batch_op.drop_column('leave_days')
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###
