"""Add age and identifier to patients

Revision ID: baceb6e2c13c
Revises: c96374104663
Create Date: 2025-06-25 14:05:43.127674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baceb6e2c13c'
down_revision = 'c96374104663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('doctor')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('doctor_notes', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('identifier', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('identifier')
        batch_op.drop_column('age')

    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('doctor_notes', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('doctor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
