"""Add doctor_id to EmergencyRequest

Revision ID: efe43dfb17ba
Revises: 74c13ed8699d
Create Date: 2025-06-28 11:41:56.342505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe43dfb17ba'
down_revision = '74c13ed8699d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_emergencies_doctor_id_doctors'), 'doctors', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_emergencies_doctor_id_doctors'), type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
